name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main-staging

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          cd client
          npm install
      - name: Lint code
        run: |
          cd client
          npm run lint
      - name: Build code
        run: |
          cd client
          npm run build
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/github-action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_LUXORANOVA9 }}'
          channelId: live
          projectId: luxoranova9
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
